import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {} from "next/navigation";
import { ThemeLayout } from "widgets/layouts";
import { DEFAULT_LANGUAGE, LanguageEnum } from "@entities/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
  params: { lang: LanguageEnum };
}>;

export default function RootLayout({
  children,
  params: { lang = DEFAULT_LANGUAGE },
}: Props) {
  return (
    <html lang={lang}>
      <ThemeLayout className={inter.className}>{children}</ThemeLayout>
    </html>
  );
}
