name: Next.js Lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci --force

    - name: Run Next.js Lint
      run: npm run lint

    - name: Run Jest tests
      run: npm run test:ci
